// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestMVC4App.Templates
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Globalization;
    using TestMVC4App.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class SummaryReport : SummaryReportBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<html>\r\n<head></head>\r\n<body>\r\n\t<h1 id=\"top\">Summary Report</h1>\r\n\t<hr/>\r\n\t<h2>Ov" +
                    "erview</h2>\r\n\t<p>Count of user profiles tested : ");
            
            #line 15 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SummaryReportDataObject.CountProfilesTested.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n\tTotal count of tests run : ");
            
            #line 16 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SummaryReportDataObject.CountTestsRun.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n\tCount of tests per user profile : ");
            
            #line 17 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SummaryReportDataObject.CountTestsPerUser.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n\tCount of user profiles free from any kind of warning : ");
            
            #line 18 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SummaryReportDataObject.CountProfilesWithoutWarnings.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n\tDuration : ");
            
            #line 19 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SummaryReportDataObject.Duration.ToString("hh'h: 'mm'mn:'ss's:'FFFFFFF")));
            
            #line default
            #line hidden
            this.Write(@"</p>
	<br/>
	<table style=""border:solid 2px lightgrey;border-collapse:collapse;"">
		<tr>
		<th style=""background-color:lightgrey;"">Result</th>
		<th style=""background-color:lightgrey;"">Count</th>
		<th style=""background-color:lightgrey;"">Description</th>
		</tr>
		");
            
            #line 27 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 foreach (KeyValuePair<ResultSeverityType,int> countPerSeverity in SummaryReportDataObject.CountBySeverity) { 
            
            #line default
            #line hidden
            this.Write("\t\t<tr>\r\n\t\t\t");
            
            #line 29 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 switch (countPerSeverity.Key) {
			case ResultSeverityType.FALSE_POSITIVE : 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: green;color:white;border-width:2px;b" +
                    "order-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 31 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 32 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
			case ResultSeverityType.WARNING: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: beige;color:black;border-width:2px;b" +
                    "order-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 34 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 35 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
			case ResultSeverityType.ERROR_WITH_EXPLANATION: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: orange;color:white;border-width:2px;" +
                    "border-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 37 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 38 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
			case ResultSeverityType.ERROR: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: Red;color:white;border-width:2px;bor" +
                    "der-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 40 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 41 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
			default: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;color:black;border-width:2px;border-color:lightgrey;bo" +
                    "rder-style:solid;font-weight:bold;\">");
            
            #line 43 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 44 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
		} 
            
            #line default
            #line hidden
            this.Write("\t\t</td>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;borde" +
                    "r-style:solid;\">");
            
            #line 47 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Value.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;border-" +
                    "style:solid;color:darkgrey;\">");
            
            #line 48 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LogManager.GetDescription(countPerSeverity.Key)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t</tr>\r\n\t");
            
            #line 50 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</table>\r\n\t<br/>\r\n\t<br/>\r\n\t<table style=\"border:solid 2px lightgrey;border-colla" +
                    "pse:collapse;\">\r\n\t<tr>\r\n\t\t<th style=\"background-color:lightgrey;\">Identified Dat" +
                    "a Behavior</th>\r\n\t\t<th style=\"background-color:lightgrey;\">Count</th>\r\n\t</tr>\r\n\t" +
                    "");
            
            #line 59 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 var sortedDictionary = SummaryReportDataObject.CountByIdentifiedDataBehavior.OrderByDescending(x => x.Value).ToDictionary(x => x.Key, x => x.Value);
	foreach (KeyValuePair<IdentifiedDataBehavior,int> countPerIdentifiedDataBehavior in sortedDictionary) {
		if(countPerIdentifiedDataBehavior.Value > 0) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;border-" +
                    "style:solid;\">");
            
            #line 63 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LogManager.GetDescription(countPerIdentifiedDataBehavior.Key)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;border-" +
                    "style:solid;\">");
            
            #line 64 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerIdentifiedDataBehavior.Value.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t</tr>\r\n\t");
            
            #line 66 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } } 
            
            #line default
            #line hidden
            this.Write(@"	</table>
	<br/>
	<br/>
	<br/>
	<hr/>
	<table style=""border:solid 2px lightgrey;border-collapse:collapse;"">
	<tr>
	<th style=""background-color:lightgrey;"">Test Name</th>
	<th style=""background-color:lightgrey;"">Success</th>
	<th style=""background-color:lightgrey;"">Sample Data</th>
	<th style=""background-color:lightgrey;"">More Info</th>
	</tr>
	");
            
            #line 79 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 foreach (string testName in SummaryReportDataObject.TestNames) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n\t\t<td style=\"padding: 10px;color:black;border-width:2px;border-color:light" +
                    "grey;border-style:solid;\">");
            
            #line 81 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testName));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t<td style=\"padding: 10px;color:black;border-width:2px;border-color:light" +
                    "grey;border-style:solid;\">\r\n\t\t\t");
            
            #line 83 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 double countTotalNotErrors = 0;
			foreach (KeyValuePair<ResultSeverityType,int> countPerSeverity in SummaryReportDataObject.CountBySeverity_ByTestName[testName]) {
				if(countPerSeverity.Key == ResultSeverityType.SUCCESS || countPerSeverity.Key == ResultSeverityType.WARNING || countPerSeverity.Key == ResultSeverityType.FALSE_POSITIVE) {
					countTotalNotErrors += countPerSeverity.Value;
			} }
			double frequencyNoErrors = countTotalNotErrors /(double) SummaryReportDataObject.CountProfilesTested; 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 89 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(frequencyNoErrors.ToString("P")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t</td>\r\n\t\t<td style=\"padding: 10px;color:black;border-width:2px;border-color:l" +
                    "ightgrey;border-style:solid;width: 40%;\">\r\n\t\t\t");
            
            #line 92 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 if(SummaryReportDataObject.SampleData_ByTestName.ContainsKey(testName)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 93 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SummaryReportDataObject.SampleData_ByTestName[testName]));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 94 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</td> \r\n\t\t<td style=\"padding: 10px;color:black;border-width:2px;border-color:li" +
                    "ghtgrey;border-style:solid;\">\r\n\t\t\t<a href=\"#");
            
            #line 97 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testName));
            
            #line default
            #line hidden
            this.Write("\">Test Overview</a><br/>\r\n\t\t\t<a href=\"C:\\\\QA_LOGS\\");
            
            #line 98 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testName));
            
            #line default
            #line hidden
            this.Write("_1.html\">Test Details</a>\r\n\t\t</td>\r\n\t</tr>\r\n\t");
            
            #line 101 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</table>\r\n\t<br/>\r\n\t");
            
            #line 104 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 foreach (string testName in SummaryReportDataObject.TestNames) { 
            
            #line default
            #line hidden
            this.Write("\t<hr/>\r\n\t<p><a href=\"#top\">Back to top</a></p>\r\n\t<h2><a id=\"#");
            
            #line 107 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 107 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testName));
            
            #line default
            #line hidden
            this.Write(@"</a></h2>
	<table style=""border:solid 2px lightgrey;border-collapse:collapse;"">
	<tr>
		<th style=""background-color:lightgrey;"">Result Severity</th>
		<th style=""background-color:lightgrey;"">Count</th>
		<th style=""background-color:lightgrey;"">Frequency</th>
	</tr>
	");
            
            #line 114 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 foreach (KeyValuePair<ResultSeverityType,int> countPerSeverity in SummaryReportDataObject.CountBySeverity_ByTestName[testName]) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n\t");
            
            #line 116 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 switch (countPerSeverity.Key) {
		case ResultSeverityType.FALSE_POSITIVE : 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: green;color:white;border-width:2px;b" +
                    "order-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 118 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 119 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
		case ResultSeverityType.WARNING: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: beige;color:black;border-width:2px;b" +
                    "order-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 121 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 122 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
		case ResultSeverityType.ERROR_WITH_EXPLANATION: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: orange;color:white;border-width:2px;" +
                    "border-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 124 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 125 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
		case ResultSeverityType.ERROR: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;background-color: Red;color:white;border-width:2px;bor" +
                    "der-color:lightgrey;border-style:solid;font-weight:bold;\">");
            
            #line 127 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 128 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
		default: 
            
            #line default
            #line hidden
            this.Write("\t\t<td style=\"padding: 10px;color:black;border-width:2px;border-color:lightgrey;bo" +
                    "rder-style:solid;font-weight:bold;\">");
            
            #line 130 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Key));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 131 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 break;
	} 
            
            #line default
            #line hidden
            this.Write("\t\t</td>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;borde" +
                    "r-style:solid;\">");
            
            #line 134 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerSeverity.Value.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;border-" +
                    "style:solid;\">\r\n\t\t\t");
            
            #line 136 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 double frequency = (double)countPerSeverity.Value /(double) SummaryReportDataObject.CountProfilesTested;
			if (frequency > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 138 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(frequency.ToString("P")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 139 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</td>\r\n\t</tr>\r\n\t");
            
            #line 142 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</table>\r\n\t<br/>\r\n\t<br/>\r\n\t<table style=\"border:solid 2px lightgrey;border-colla" +
                    "pse:collapse;\">\r\n\t<tr>\r\n\t\t<th style=\"background-color:lightgrey;\">Identified Dat" +
                    "a Behavior</th>\r\n\t\t<th style=\"background-color:lightgrey;\">Count</th>\r\n\t</tr>\r\n\t" +
                    "");
            
            #line 151 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 if(SummaryReportDataObject.CountByIdentifiedDataBehavior_ByTestName.ContainsKey(testName)) {
	var sortedDictionary2 =SummaryReportDataObject.CountByIdentifiedDataBehavior_ByTestName[testName].OrderByDescending(x => x.Value).ToDictionary(x => x.Key, x => x.Value);
	foreach (KeyValuePair<IdentifiedDataBehavior,int> countPerIdentifiedDataBehavior in sortedDictionary2) {
		if(countPerIdentifiedDataBehavior.Value > 0) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;border-" +
                    "style:solid;\">");
            
            #line 156 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LogManager.GetDescription(countPerIdentifiedDataBehavior.Key)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t<td style=\"padding: 10px;border-width:2px;border-color:lightgrey;border-" +
                    "style:solid;\">");
            
            #line 157 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(countPerIdentifiedDataBehavior.Value.ToString("{0:D}", CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t</tr>\r\n\t");
            
            #line 159 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } } } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 161 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "\\psf\Home\Desktop\TestMVC4App\Profile-System-Testing\TestMVC4App\Templates\SummaryReport.tt"

private global::TestMVC4App.Templates.SharedSummaryReportData _SummaryReportDataObjectField;

/// <summary>
/// Access the SummaryReportDataObject parameter of the template.
/// </summary>
private global::TestMVC4App.Templates.SharedSummaryReportData SummaryReportDataObject
{
    get
    {
        return this._SummaryReportDataObjectField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool SummaryReportDataObjectValueAcquired = false;
if (this.Session.ContainsKey("SummaryReportDataObject"))
{
    this._SummaryReportDataObjectField = ((global::TestMVC4App.Templates.SharedSummaryReportData)(this.Session["SummaryReportDataObject"]));
    SummaryReportDataObjectValueAcquired = true;
}
if ((SummaryReportDataObjectValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("SummaryReportDataObject");
    if ((data != null))
    {
        this._SummaryReportDataObjectField = ((global::TestMVC4App.Templates.SharedSummaryReportData)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class SummaryReportBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
