using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestMVC4App.Models
{
    public enum EnumTestUnitNames
    {
            UserBasicInfo_LastName,
            UserBasicInfo_FirstName,
            UserBasicInfo_MiddleName,
            UserBasicInfo_Email,
            UserBasicInfo_NetId,
            UserBasicInfo_PageName,
            UserBasicInfo_Suffix,
            UserBasicInfo_Idx,
            UserBasicInfo_LicenseNumber,
            UserBasicInfo_Npi,
            UserBasicInfo_Gender,
            UserBasicInfo_UPI,
            UserGeneralInfo_Bio,
            UserGeneralInfo_Titles,
            UserGeneralInfo_Languages,
            UserGeneralInfo_AltFirstName,
            UserGeneralInfo_AltMiddleName,
            UserGeneralInfo_AltMiddleNameDisplayed,
            UserGeneralInfo_AltLastName,
            UserGeneralInfo_AltSuffix,
            UserGeneralInfo_Suffixes,
            UserGeneralInfo_CVs_Count,
            UserGeneralInfo_Organizations_Id,
            UserGeneralInfo_Organizations_Name,
            UserGeneralInfo_Organizations_IdAndName,
            UserGeneralInfo_Organizations_TreeDepthCoherence,
            //UserGeneralInfo_Organizations_IsImportedPrimary,
            UserGeneralInfo_Organizations_TreeMerged,
            UserGeneralInfo_Organizations_Type,
            UserGeneralInfo_Organizations_Missions,
            //UserContactLocationInfo_Assistants,
            UserContactLocationInfo_LabWebsites_Names,
            UserContactLocationInfo_LabWebsites_Links,
            UserContactLocationInfo_Addresses,
            UserContactLocationInfo_Addresses_Geo,
            UserContactLocationInfo_Addresses_StreetAddress,
            UserContactLocationInfo_Addresses_ZipCodes,
            UserContactLocationInfo_Addresses_IsMailing,
            UserPublicationInfo_Titles,
            UserPublicationInfo_Citations,
            UserResearchInfo_Summary,
            UserResearchInfo_Overview,
            UserEducationTrainingInfo_Trainings,
            UserEducationTrainingInfo_Education,
            UserHonorServiceInfo_Honors,
            UserHonorServiceInfo_Services,
            UserPatientCareInfo_AcceptedReferral,
            UserPatientCareInfo_BoardCertifications,
            UserPatientCareInfo_CancersTreated,
            UserPatientCareInfo_MyChart,
            UserPatientCareInfo_IsSeeingNewPatients,
            UserPatientCareInfo_IsSeeingPatientType,
            UserPatientCareInfo_PhysicianBio,
            UserResearchInfo_PublicHealthKeywords
    }
}